// garra_ang/src/app/features/auth/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';

import { SessaoService } from '../../../core/services';
import { AutenticacaoService } from '../autenticacao.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly autenticacaoService = inject(AutenticacaoService);
  private readonly sessaoService = inject(SessaoService);
  private readonly router = inject(Router);
  private readonly rota = inject(ActivatedRoute);

  readonly carregando = signal(false);
  readonly erro = signal<string | null>(null);
  readonly cadastroConcluido = signal(this.rota.snapshot.queryParamMap.get('registrado') === '1');

  readonly formulario = this.fb.nonNullable.group({
    login: ['', [Validators.required]],
    senha: ['', [Validators.required]],
  });

  campoInvalido(nome: 'login' | 'senha'): boolean {
    const campo = this.formulario.get(nome);
    return !!campo && campo.invalid && (campo.dirty || campo.touched);
  }

  entrar(): void {
    if (this.formulario.invalid) {
      this.formulario.markAllAsTouched();
      return;
    }

    this.carregando.set(true);
    this.erro.set(null);
    this.cadastroConcluido.set(false);

    this.autenticacaoService
      .login(this.formulario.getRawValue())
      .pipe(finalize(() => this.carregando.set(false)))
      .subscribe({
        next: (token) => {
          this.sessaoService.salvarToken(token.token);
          this.router.navigateByUrl('/professores');
        },
        error: (erro: Error) => this.erro.set(erro.message),
      });
  }
}

<section
  class="flex min-h-screen items-center justify-center bg-gradient-to-br from-indigo-50 via-white to-amber-50 px-4 py-12"
>
  <div class="w-full max-w-md rounded-2xl border border-indigo-100 bg-white p-8 shadow-xl shadow-indigo-100/50">
    <div class="mb-8 text-center">
      <span class="text-4xl">🎓</span>
      <h1 class="mt-2 text-2xl font-bold text-indigo-900">Bem-vindo de volta</h1>
      <p class="mt-1 text-sm text-gray-500">Acesse o painel do cursinho Garra</p>
    </div>

    @if (cadastroConcluido()) {
      <div class="mb-6 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">
        Cadastro realizado com sucesso! Faça login para continuar.
      </div>
    }

    @if (erro()) {
      <div class="mb-6 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
        {{ erro() }}
      </div>
    }

    <form [formGroup]="formulario" (ngSubmit)="entrar()" class="space-y-5" novalidate>
      <div>
        <label for="login" class="mb-1 block text-sm font-medium text-gray-700">Login</label>
        <input
          id="login"
          type="text"
          formControlName="login"
          autocomplete="username"
          class="w-full rounded-lg border px-3 py-2 text-sm text-gray-800 shadow-sm focus:outline-none focus:ring-2"
          [class.border-gray-300]="!campoInvalido('login')"
          [class.focus:ring-indigo-500]="!campoInvalido('login')"
          [class.border-red-400]="campoInvalido('login')"
          [class.focus:ring-red-400]="campoInvalido('login')"
        />
        @if (campoInvalido('login')) {
          <p class="mt-1 text-xs text-red-600">Informe seu login.</p>
        }
      </div>

      <div>
        <label for="senha" class="mb-1 block text-sm font-medium text-gray-700">Senha</label>
        <input
          id="senha"
          type="password"
          formControlName="senha"
          autocomplete="current-password"
          class="w-full rounded-lg border px-3 py-2 text-sm text-gray-800 shadow-sm focus:outline-none focus:ring-2"
          [class.border-gray-300]="!campoInvalido('senha')"
          [class.focus:ring-indigo-500]="!campoInvalido('senha')"
          [class.border-red-400]="campoInvalido('senha')"
          [class.focus:ring-red-400]="campoInvalido('senha')"
        />
        @if (campoInvalido('senha')) {
          <p class="mt-1 text-xs text-red-600">Informe sua senha.</p>
        }
      </div>

      <button
        type="submit"
        [disabled]="carregando()"
        class="flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60"
      >
        @if (carregando()) {
          <span class="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"></span>
          Entrando...
        } @else {
          Entrar
        }
      </button>
    </form>

    <p class="mt-6 text-center text-sm text-gray-500">
      Ainda não tem conta?
      <a routerLink="/registro" class="font-medium text-indigo-600 hover:text-indigo-800">Cadastre-se</a>
    </p>
  </div>
</section>

// frontend-garra/src/views/Login.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { persistAuthToken } from '../auth/session';
import { AuthService } from '../services/api';
import { toast } from 'sonner';

export default function Login() {
  const [login, setLogin] = useState('');
  const [senha, setSenha] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const { data } = await AuthService.login({ login, senha });
      const token = data?.token;
      if (token && persistAuthToken(token)) {
        toast.success('Login realizado com sucesso!');
        navigate('/', { replace: true });
        return;
      }
      toast.error('Token inválido ou expirado. Tente novamente.');
    } catch (error) {
      console.error(error);
      if (axios.isAxiosError(error)) {
        const status = error.response?.status;
        if (status === 401 || status === 403) {
          toast.error('Login ou senha incorretos.');
          return;
        }
      }
      toast.error('Não foi possível conectar. Verifique se o backend está no ar.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-[#f8fafc] dark:bg-gray-900 p-4">
      <div className="w-full max-w-md space-y-6 rounded-xl bg-white dark:bg-gray-800 p-8 shadow-lg">
        <h2 className="text-center text-3xl font-bold text-gray-900 dark:text-white">Login</h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Login</label>
            <input
              type="text"
              value={login}
              onChange={(e) => setLogin(e.target.value)}
              required
              className="mt-1 w-full rounded-md border border-gray-300 bg-white px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Senha</label>
            <input
              type="password"
              value={senha}
              onChange={(e) => setSenha(e.target.value)}
              required
              className="mt-1 w-full rounded-md border border-gray-300 bg-white px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:border-gray-600 dark:bg-gray-700"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-xl bg-indigo-600 py-2 text-white hover:bg-indigo-700 disabled:opacity-50"
          >
            {loading ? 'Entrando...' : 'Entrar'}
          </button>
        </form>
        <p className="mt-4 text-center text-sm text-gray-600 dark:text-gray-400">
          Ainda não tem conta?{' '}
          <Link to="/register" className="font-medium text-indigo-600 hover:underline dark:text-indigo-400">
            Registrar
          </Link>
        </p>
      </div>
    </div>
  );
}
